name: JMeter Tests

on: [push]

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/download-artifact@v3
        with:
          name: jmeter
          path: C:\Users\ocina\OneDrive\Masa端st端\apache-jmeter-5.4.1\apache-jmeter-5.4.1\bin\ApacheJMeter.jar
      - uses: apache/jmeter@v1
        with:
          testFilePath: 'C:\Users\ocina\OneDrive\Masa端st端\SimpleEx.jmx'
