name: JMeter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      virtual_user:
        required: true
        description: Enter virtual user count
        default: '5'
      ramp_up_time:
        required: true
        description: Enter ramp up time
        default: '1'
      loop_count:
        required: true
        description: Enter loop count
        default: '1'

jobs:
  run_jmeter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run JMeter test
        run: |
          ./jmeter -n -t ./userNamePassword.jmx -e -o ./reports\report1

    
