name: JMeter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      virtual_user:
        required: true
        description: Enter virtual user count
        default: '5'
      ramp_up_time:
        required: true
        description: Enter ramp up time
        default: '1'
      loop_count:
        required: true
        description: Enter loop count
        default: '1'

jobs:
  run_jmeter_test:
    runs-on: ubuntu-latest

    steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Run Specified Features 
            run: >
                cd /Users/oguzcinar/Desktop/Cinar/apache-jmeter-5.6.3/bin;
                ./jmeter -n -t /Users/oguzcinar/Desktop/Cinar/JMeter/userNamePassword.jmx -l /Users/oguzcinar/Desktop/Cinar/JMeter/reports\csvReports\result1.csv -e -o /Users/oguzcinar/Desktop/Cinar/JMeter/reports\htmlReports\report1;
